### ISSUE TITLE
合并出现问题，求大佬解答。

### ISSUE THREAD

**Issue by xie895132650** [yelog/layui-table-merge#2]
![image](https://user-images.githubusercontent.com/42328320/54740671-08505b00-4bf7-11e9-8966-6383821ec8c8.png)
![image](https://user-images.githubusercontent.com/42328320/54740740-30d85500-4bf7-11e9-92e6-0d2164b38bb7.png)

**Comment by yelog** [comment]
这个合并并不会改变数据的顺序，由于图中所示两行不在一起，所以没有自动合并。

建议先进行数据排序（比如sql的order by）让此列相同数据在一起，这样就可以自动合并了。

**Comment by xie895132650** [comment]
谢谢大佬，解决了。
