### ISSUE TITLE
合并的表格，有的有空隙，不能闭合，这个怎么整？

### ISSUE THREAD

**Issue by avyou** [yelog/layui-table-merge#3]
大佬，合并的表格，有的有空隙，不能闭合，这个怎么整？
chrome 有空隙，但 firefox 是正常的

**Comment by yelog** [comment]
layui给 td 设置的样式：`position: relative` ，在chrome下会出现问题。

已在插件中强写td样式修复了这个问题，在github上更新最新的tableMerge.js即可。

复现问题demo： [https://jsbin.com/witesoyayo/2/edit?html,css,output ](https://jsbin.com/witesoyayo/2/edit?html,css,output )
